server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/khsb
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: 91d7b2d905f0e1b0a05cb28064de85b0566c43c3f7f7e5bafda20cb4e7c49dfe